--- 
apiVersion: dynatrace.com/v1alpha1
kind: DynaKube
metadata: 
  name: dynakube
  namespace: dynatrace
spec: 
  apiUrl: "https://xmq55850.live.dynatrace.com/api"
  classicFullStack: 
    enabled: true
    tolerations: 
      - 
        effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  kubernetesMonitoring: 
    enabled: true
